name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
  push:
    branches:
      - develop
    workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write



jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Actualizar README
        run: |
          echo "Añadida feature: ${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}" >> README.md

      - name: Guardar cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Actualiza README con nueva feature" || echo "No hay cambios"
          git push

  validate-dev:
    needs: update-readme
    runs-on: self-hosted

    steps:
      - name: Validar DEV_TOKEN
        run: |
          if [ "$DEV_TOKEN" = "${{ secrets.DEV_TOKEN }}" ]; then
            echo "DEV_TOKEN válido"
          else
            echo "DEV_TOKEN no coincide"
            exit 1
          fi